In [30]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sb

%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [31]:
# importing the monthly data
df_jan_avail_peak = pd.read_excel("JAN -DEC 2023 AVAILABILITY FOR OWERRI.xlsx", sheet_name= 0)
df_feb_avail_peak = pd.read_excel("JAN -DEC 2023 AVAILABILITY FOR OWERRI.xlsx", sheet_name= 1)
df_mar_avail_peak = pd.read_excel("JAN -DEC 2023 AVAILABILITY FOR OWERRI.xlsx", sheet_name= 2)

In [32]:
#importing the monthly energy data
df_jan_energy = pd.read_excel("JANUARY 2023 OWERRI ENERGY READING .xlsx")
df_feb_energy = pd.read_excel("FEBRUARY 2023 OWERRI ENERGY READING.xlsx")
df_mar_energy = pd.read_excel("MARCH 2023 OWERRI ENERGY READING.xlsx")

In [33]:
df_feb_energy.head()

,,Unnamed: 1,Unnamed: 2,0,1,2,3,4,5,6,...,22,23,24,25,26,27,28,29,30,Unnamed: 34
0,FEBRUARY,INJECTION SUB,FEEDERS,ENERGY READING MW,ENERGY READING MWH,ENERGY READING MW,ENERGY READING MWH,ENERGY READING MWH,ENERGY READING MWH,ENERGY READING MWH,...,ENERGY READING MWH,ENERGY READING MWH,ENERGY READING MWH,ENERGY READING MWH,ENERGY READING MWH,ENERGY READING MWH,ENERGY READING MWH,ENERGY READING MWH,ENERGY READING MWH,%availability
1,2023,NaN,DAYS,31/12/22,1,2,3,4,5,6,...,22,23,24,25,26,27,28,29,30,NaN
2,NaN,INTERFACE,AIRPORT 33,83817.6,84066.7,84339.3,84537.3,84727.6,84923.9,85099.9,...,89437.3,89484.9,89759.4,90038.6,90297.8,90495.8,90593.7,NaN,NaN,NaN
3,NaN,NaN,MW,NaN,249.1,272.6,198,190.3,196.3,176,...,219.6,47.6,274.5,279.2,259.2,198,97.9,NaN,0,NaN
4,NaN,NaN,AVAILABILITY,NaN,22.58,22..57,20.24,16.47,19.88,22.68,...,18.55,6.92,22.63,22.37,24,21.87,22.5,NaN,NaN,569.05

In [34]:
numbers = list(range(1, 32))
date = [num for num in numbers for _ in range(7)]
print(date)

[1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 27, 27, 27, 28, 28, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29, 29, 30, 30, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 31, 31]

In [38]:
feeders= [['GRA','TOWNSHIP','NAZE','NEW_OWERRI','FUT','IKENEGBU','EGBU']*31]b

## mark down 
# checking out stuff

In [43]:
feeders_comp =[]
for fdr in feeders:
    feeders_comp.extend(fdr)

In [ ]:
Availability=[]